GET http://127.0.0.1:8000/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNTYxNzIwLCJpYXQiOjE3NzA1NjE0MjAsImp0aSI6IjEzNjc3ZTkwNzAxZTQ1ZjM4YmY2NjhlZmUzYjNhN2JkIiwidXNlcl9pZCI6IjQifQ.d7Jf3x1fptXxRcrDLS7P0bx3D4UdvCszXCkgjvsOFMY

{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 9.99,
    "stock": 100
}

###
GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNjg4OTUyLCJpYXQiOjE3NzE2ODg2NTIsImp0aSI6ImI4MmRiNmQwZmY0YjRmMmFhMTZlNWM2ZjQxYTg5MTQwIiwidXNlcl9pZCI6IjIifQ.h8CMdXzaKrSByN4-hjuxpnrnB_YxuN4bCNRjtbcP4Oo



###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxOTUzNjU2LCJpYXQiOjE3NzE5NTMzNTYsImp0aSI6IjViNjdhYzNkNTJiNTRlOGFhMDM5ZGExMmU1YzljZDkyIiwidXNlcl9pZCI6IjIifQ.-y005ceksapggVkJd1DQW7u6vJeW008AUmg5hyuMu4o

{
    "status": "pending",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}