GET http://127.0.0.1:8000/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNTYxNzIwLCJpYXQiOjE3NzA1NjE0MjAsImp0aSI6IjEzNjc3ZTkwNzAxZTQ1ZjM4YmY2NjhlZmUzYjNhN2JkIiwidXNlcl9pZCI6IjQifQ.d7Jf3x1fptXxRcrDLS7P0bx3D4UdvCszXCkgjvsOFMY

{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 9.99,
    "stock": 100
}


###
PUT http://127.0.0.1:8000/orders/f0d79eb7-007d-4888-b059-b10d71671154/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTA2Mjg0LCJpYXQiOjE3NzIxMDU5ODQsImp0aSI6IjMxMTNjODliYzMzODQ3MWVhYmJkZDUzMDVjMTJjM2U3IiwidXNlcl9pZCI6IjIifQ.jr6aTssKUqsTSEkjrib3MzYqAAxlLoD6RON59z5B6BY

{
    "status": "completed",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}


###
GET http://127.0.0.1:8000/orders/f0d79eb7-007d-4888-b059-b10d71671154/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTA2Mjg0LCJpYXQiOjE3NzIxMDU5ODQsImp0aSI6IjMxMTNjODliYzMzODQ3MWVhYmJkZDUzMDVjMTJjM2U3IiwidXNlcl9pZCI6IjIifQ.jr6aTssKUqsTSEkjrib3MzYqAAxlLoD6RON59z5B6BY



###
DELETE  http://127.0.0.1:8000/orders/f0d79eb7-007d-4888-b059-b10d71671154/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTA2Mjg0LCJpYXQiOjE3NzIxMDU5ODQsImp0aSI6IjMxMTNjODliYzMzODQ3MWVhYmJkZDUzMDVjMTJjM2U3IiwidXNlcl9pZCI6IjIifQ.jr6aTssKUqsTSEkjrib3MzYqAAxlLoD6RON59z5B6BY
