GET http://127.0.0.1:8000/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNTYxNzIwLCJpYXQiOjE3NzA1NjE0MjAsImp0aSI6IjEzNjc3ZTkwNzAxZTQ1ZjM4YmY2NjhlZmUzYjNhN2JkIiwidXNlcl9pZCI6IjQifQ.d7Jf3x1fptXxRcrDLS7P0bx3D4UdvCszXCkgjvsOFMY

{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 9.99,
    "stock": 100
}

###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNjg4ODIwLCJpYXQiOjE3NzE2ODg1MjAsImp0aSI6IjI2MGNiYTMxYmQzODQ5NTU5N2UzZWE0Y2Y0ZWI3YTZmIiwidXNlcl9pZCI6IjYifQ.hdRPaGK4Rn45ShmAQZDCZi2X5PlcBKW8QeJLzVeTi6c